# Generated by Django 3.2.25 on 2025-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('shipping_date', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the included product.', max_length=100)),
                ('image_url', models.URLField(help_text='Image of the product.')),
                ('description', models.TextField(blank=True, help_text='Optional description shown in carousel.')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product in the box.')),
                ('box', models.ForeignKey(help_text='The box this product is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='boxes.box')),
            ],
        ),
    ]
