# Generated by Django 4.2.20 on 2025-05-11 15:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the box (must be unique)', max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('shipping_date', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the included product.', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image to represent this product.', max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True, help_text='Optional description for this product (shown in UI carousel).')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product included in the box.')),
                ('box', models.ForeignKey(blank=True, help_text='The box this product belongs to. Can be left blank if unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='boxes.box')),
            ],
        ),
    ]
