# Generated by Django 3.2.25 on 2025-04-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxproduct',
            name='box',
            field=models.ForeignKey(blank=True, help_text='The box this product is part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='boxes.box'),
        ),
    ]
