# Generated by Django 3.2.25 on 2025-04-21 17:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_alter_boxproduct_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='boxproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='box_images/'),
        ),
        migrations.AddField(
            model_name='boxproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image to represent this product.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='boxproduct',
            name='box',
            field=models.ForeignKey(blank=True, help_text='The box this product belongs to. Can be left blank if unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='boxes.box'),
        ),
        migrations.AlterField(
            model_name='boxproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this product (shown in UI carousel).'),
        ),
        migrations.AlterField(
            model_name='boxproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of this product included in the box.'),
        ),
    ]
