# Generated by Django 3.2.25 on 2025-04-21 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20250421_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
