# Generated by Django 4.2.20 on 2025-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_alter_box_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Descriptive text for the box image (for accessibility and SEO).', max_length=150),
        ),
        migrations.AddField(
            model_name='boxproduct',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Descriptive text for the product image(for accessibility and SEO).', max_length=150),
        ),
    ]
