# Generated by Django 4.2.20 on 2025-04-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_box_image_alt_boxproduct_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='boxproduct',
            name='image_alt',
        ),
    ]
