# Generated by Django 4.2.20 on 2025-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_remove_box_image_alt_remove_boxproduct_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(help_text='Name of the box (must be unique)', max_length=100, unique=True),
        ),
    ]
