# Generated by Django 4.2.20 on 2025-05-11 15:06

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_f_name', models.CharField(help_text='First name of the recipient.', max_length=30)),
                ('recipient_l_name', models.CharField(help_text='Last name of the recipient.', max_length=30)),
                ('address_line_1', models.CharField(help_text='First line of the address (e.g., house number and street name).', max_length=60)),
                ('address_line_2', models.CharField(blank=True, help_text='Additional address info e.g., apt or suit (optional).', max_length=60)),
                ('town_or_city', models.CharField(help_text='City or town name.', max_length=40)),
                ('county', models.CharField(blank=True, help_text='County, region or administrative area.', max_length=50)),
                ('postcode', models.CharField(help_text='Postal or ZIP code (varies by country).', max_length=10)),
                ('country', django_countries.fields.CountryField(help_text='Select your country from the list.', max_length=2)),
                ('phone_number', models.CharField(help_text='Contact number for delivery issues.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Check this box if this is your default delivery address')),
                ('is_gift_address', models.BooleanField(default=False, help_text='Check this box if this is an address used for a gift')),
                ('label', models.CharField(blank=True, help_text='e.g. Home, Work, Parents', max_length=50)),
                ('user', models.ForeignKey(help_text='The user this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
