# Generated by Django 3.2.25 on 2025-04-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_f_name', models.CharField(help_text='First name of the recipient.', max_length=100)),
                ('recipient_l_name', models.CharField(help_text='Last name of the recipient.', max_length=100)),
                ('address_line_1', models.CharField(help_text='First line of the address - eg house number and street name.', max_length=80)),
                ('address_line_2', models.CharField(blank=True, help_text='Additional address info eg apt or suit (optional)', max_length=80, null=True)),
                ('town_or_city', models.CharField(help_text='City or town name.', max_length=40)),
                ('county', models.CharField(help_text='County, region or administrative area.', max_length=80)),
                ('postcode', models.CharField(help_text='Postal code or ZIP.', max_length=20)),
                ('country', models.CharField(help_text='Country name from a list.', max_length=100)),
                ('phone_number', models.CharField(help_text='Contact number for delivery issues.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Check this box if this is your default delivery address')),
                ('user', models.ForeignKey(help_text='The user this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
