# Generated by Django 3.2.25 on 2025-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
    ]
