# Generated by Django 3.2.25 on 2025-04-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shippingaddress_is_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_billing',
        ),
    ]
