# Generated by Django 3.2.25 on 2025-04-21 20:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_shippingaddress_is_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Select your country from the list.', max_length=2, null=True),
        ),
    ]
