# Generated by Django 4.2.20 on 2025-04-25 20:16

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(
                max_length=20,
                help_text="Contact number for delivery issues."
            ),
        ),
    ]
