# Generated by Django 4.2.20 on 2025-04-25 20:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact number for delivery issues.', max_length=128, region=None),
        ),
    ]
