# Generated by Django 4.2.20 on 2025-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(help_text='Contact number for delivery issues.', max_length=20),
        ),
    ]
