# Generated by Django 4.2.20 on 2025-04-28 00:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_1',
            field=models.CharField(help_text='First line of the address (e.g., house number and street name).', max_length=80),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, default='', help_text='Additional address info e.g., apt or suit (optional).', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='GB', help_text='Select your country from the list.', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='county',
            field=models.CharField(blank=True, help_text='County, region or administrative area.', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(help_text='Contact number for delivery issues.', max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(help_text='Postal code or ZIP.', max_length=12),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_f_name',
            field=models.CharField(help_text='First name of the recipient.', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_l_name',
            field=models.CharField(help_text='Last name of the recipient.', max_length=50),
        ),
    ]
