# Generated by Django 4.2.20 on 2025-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_1',
            field=models.CharField(help_text='First line of the address (e.g., house number and street name).', max_length=60),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Additional address info e.g., apt or suit (optional).', max_length=60),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(help_text='Contact number for delivery issues.', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(help_text='Postal code or ZIP.', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_f_name',
            field=models.CharField(help_text='First name of the recipient.', max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_l_name',
            field=models.CharField(help_text='Last name of the recipient.', max_length=30),
        ),
    ]
