# Generated by Django 4.2.20 on 2025-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_gift_address',
            field=models.BooleanField(default=False, help_text='Check this box if this is an address used for a gift'),
        ),
    ]
