# Generated by Django 4.2.20 on 2025-05-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_shippingaddress_is_gift_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='label',
            field=models.CharField(blank=True, help_text='e.g. Home, Work, Parents', max_length=50),
        ),
    ]
