# Generated by Django 4.2.20 on 2025-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_shippingaddress_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(help_text='Postal or ZIP code (varies by country).', max_length=10),
        ),
    ]
