# Generated by Django 3.2.25 on 2025-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionmeta',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
