# Generated by Django 4.2.20 on 2025-04-28 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_shippingaddress_address_line_1_and_more'),
        ('orders', '0002_auto_20250414_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionmeta',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress'),
        ),
    ]
