# Generated by Django 4.2.20 on 2025-05-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0002_alter_stripesubscriptionmeta_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripesubscriptionmeta",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.shippingaddress",
            ),
        ),
    ]
