# Generated by Django 4.2.20 on 2025-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_stripesubscriptionmeta_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripesubscriptionmeta",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
