# Generated by Django 4.2.20 on 2025-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
